---
- name: Manage NGINX service
  hosts: node
  become: yes
  tasks:
    - name: Ensure NGINX is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Restart NGINX if needed
      ansible.builtin.service:
        name: nginx
        state: restarted
